# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data-definitions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64\x61ta-definitions.proto\"@\n\tFinditMap\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x19\n\x04maps\x18\x03 \x03(\x0b\x32\x0b.PartialMap\"l\n\nPartialMap\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nimage_link\x18\x03 \x01(\t\x12\x17\n\x05nodes\x18\x04 \x01(\x0b\x32\x08.MapNode\x12\x17\n\x05\x65\x64ges\x18\x05 \x01(\x0b\x32\x08.MapEdge\"G\n\x07MapNode\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\t\n\x01x\x18\x04 \x01(\x02\x12\t\n\x01y\x18\x05 \x01(\x02\"K\n\x07MapEdge\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tfrom_node\x18\x02 \x01(\x02\x12\x0f\n\x07to_node\x18\x03 \x01(\x02\x12\x10\n\x08\x64istance\x18\x04 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_definitions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FINDITMAP._serialized_start=26
  _FINDITMAP._serialized_end=90
  _PARTIALMAP._serialized_start=92
  _PARTIALMAP._serialized_end=200
  _MAPNODE._serialized_start=202
  _MAPNODE._serialized_end=273
  _MAPEDGE._serialized_start=275
  _MAPEDGE._serialized_end=350
# @@protoc_insertion_point(module_scope)
