# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data-consumer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import data_definitions_pb2 as data__definitions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x61ta-consumer.proto\x1a\x16\x64\x61ta-definitions.proto\"\x1e\n\x0eRecieveRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"E\n\x0cRecieveReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1c\n\x03map\x18\x02 \x01(\x0b\x32\n.FinditMapH\x00\x88\x01\x01\x42\x06\n\x04_map2:\n\x08\x43onsumer\x12.\n\nRecieveMap\x12\x0f.RecieveRequest\x1a\r.RecieveReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_consumer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECIEVEREQUEST._serialized_start=47
  _RECIEVEREQUEST._serialized_end=77
  _RECIEVEREPLY._serialized_start=79
  _RECIEVEREPLY._serialized_end=148
  _CONSUMER._serialized_start=150
  _CONSUMER._serialized_end=208
# @@protoc_insertion_point(module_scope)
