# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_consumer_pb2 as data__consumer__pb2


class ConsumerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecieveMap = channel.unary_unary(
                '/Consumer/RecieveMap',
                request_serializer=data__consumer__pb2.RecieveRequest.SerializeToString,
                response_deserializer=data__consumer__pb2.RecieveReply.FromString,
                )


class ConsumerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecieveMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsumerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecieveMap': grpc.unary_unary_rpc_method_handler(
                    servicer.RecieveMap,
                    request_deserializer=data__consumer__pb2.RecieveRequest.FromString,
                    response_serializer=data__consumer__pb2.RecieveReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Consumer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Consumer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecieveMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Consumer/RecieveMap',
            data__consumer__pb2.RecieveRequest.SerializeToString,
            data__consumer__pb2.RecieveReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
