# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data-provider.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import data_definitions_pb2 as data__definitions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x61ta-provider.proto\x1a\x16\x64\x61ta-definitions.proto\"*\n\x0fRegisterRequest\x12\x17\n\x03map\x18\x01 \x01(\x0b\x32\n.FinditMap\" \n\rRegisterReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32=\n\x08Provider\x12\x31\n\x0bRegisterMap\x12\x10.RegisterRequest\x1a\x0e.RegisterReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_provider_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERREQUEST._serialized_start=47
  _REGISTERREQUEST._serialized_end=89
  _REGISTERREPLY._serialized_start=91
  _REGISTERREPLY._serialized_end=123
  _PROVIDER._serialized_start=125
  _PROVIDER._serialized_end=186
# @@protoc_insertion_point(module_scope)
